version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: docker/ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama-init.sh:/ollama-init.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/ollama-init.sh"]

volumes:
  qdrant_storage:
    driver: local
  ollama_data:
    driver: local 